# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/llm_context',
                'doc_host': 'https://radekosmulski.github.io',
                'git_url': 'https://github.com/radekosmulski/llm_context',
                'lib_path': 'llm_context'},
  'syms': {'llm_context.core': {'llm_context.core.foo': ('core.html#foo', 'llm_context/core.py')}}}
